### ISSUE TITLE
cvx error

### ISSUE THREAD

**Issue by gregoriog** [epnev/ca_source_extraction#15]
Hello, I was trying your code and I can't make it work because I have a cvx error when I run the demo_script. I was wondering if I have the wrong version of cvx or if there might be something else that I should take into account when running the script. Thanks for your time. Here is the output of the command window in matlab:

>> demo_script
Reading from frame 1 to frame 2000 of 2000 total frames
Finished reading images
Estimating the noise power for each pixel from a simple PSD estimate...  done 
No spatial downsampling is performed. Consider spatial downsampling if the field of view is very large. 
No temporal downsampling is performed. Consider temporal downsampling if the recording is very long. 
starting resampling 
Initializing components with greedy method 
found 10 out of 30 neurons..
found 20 out of 30 neurons..
found 30 out of 30 neurons..
Refining initial estimates with HALS...  done 
Starting parallel pool (parpool) using the 'local' profile ... connected to 12 workers.
Updated spatial components 
Error using cvx_global (line 76)
Struct contents reference from a non-struct array object.

Error in cvxprob (line 4)
cvx_global

Error in cvx_begin (line 41)
assignin( 'caller', 'cvx_problem', cvxprob( varargin{:} ) );

Error in cvx_foopsi (line 20)
    cvx_begin quiet

Error in constrained_foopsi (line 178)
                [c(:,rep),bas(rep),cin(rep)] = cvx_foopsi(y,b,c1,sn,b_lb,g,w_,~mis_data);

Error in update_temporal_components (line 178)
            parfor jj = 1:length(O{jo})

Error in demo_script (line 61)
[C,f,P,S] = update_temporal_components(Yr,A,b,Cin,fin,P,options);

**Comment by epnev** [comment]
@gregoriog 
Hi, have you installed cvx properly, i.e., run cvx_setup from inside the cxv folder after downloading it so all the routines are loaded? Check this for more info: http://cvxr.com/cvx/doc/install.html

**Comment by gregoriog** [comment]
Thank you very much for your response. I hadn't installed cvx properly. Now
it works.

Have a nice weekend


Gregorio
d*!*b
