### ISSUE TITLE
bug in merge_components when not using fast_merge

### ISSUE THREAD

**Issue by jpakan** [epnev/ca_source_extraction#17]
There seems to be a small bug in `merge_components` when the flag for `fast_merge` is set to 0: the order of outputs for the `update_temporal_components` function is wrong (presumably left over from when `Y_res` was removed as an output).

changing `merge_components` line 103  to:
 `[cc,~,Ptemp,ss] = update_temporal_components(Y_res(ff,:),aa(ff),bb(ff,:),cc,f,Pmr,options);` fixes the problem.

Thanks for the nice resource.

**Comment by epnev** [comment]
Thanks @jpakan you're right. This is fixed now.
