### ISSUE TITLE
Error using cvxprob

### ISSUE THREAD

**Issue by jafphd** [epnev/ca_source_extraction#20]
Hi,
I got the following error when trying to execute the demo_script. I executed cvx_setup as you suggested and the script reports no problem. I would appreciate very much if you can help me on this issue.
Thanks

Error using cvxprob (line 48)
Struct contents reference from a non-struct array object.

Error in cvx_begin (line 41)
assignin( 'caller', 'cvx_problem', cvxprob( varargin{:} ) );

Error in cvx_foopsi (line 20)
    cvx_begin quiet

Error in constrained_foopsi (line 178)
                [c(:,rep),bas(rep),cin(rep)] = cvx_foopsi(y,b,c1,sn,b_lb,g,w_,~mis_data);

Error in update_temporal_components (line 199)
            parfor jj = 1:length(O{jo})

Error in demo_script (line 63)
[C,f,P,S] = update_temporal_components(Yr,A,b,Cin,fin,P,options);

**Comment by epnev** [comment]
Hi @jafphd 
I searched for the error message you got and there might be some installation issues. See for example here: http://stackoverflow.com/questions/26191167/matlab-cvx-error-with-cvx-begin
Can you run the cvx quickstart examples without problems as explained in this page?

**Comment by jafphd** [comment]
Thank you @epnev, I finally got the demo_script working as expected. I do not why but after trying several times running the script in Matlab R2015b (Win10), I've got to the error at cvxprob. This happened after the installation. But, after rebooting the system, I succeeded. All the best!

**Comment by epnev** [comment]
good to hear!
