### ISSUE TITLE
error in make_patch_video

### ISSUE THREAD

**Issue by vd2309** [epnev/ca_source_extraction#26]
Hi!

I get this error when I try to run make_patch_video:

**make_patch_video(A_or,C_or,b2,f2,Yr,Coor,options)
Error using reshape
Size can only have one unknown dimension.

Error in make_patch_video (line 64)
    Y = reshape(Y,d1,d2,T);**

I dont know why it is givng me this error, since d1, d2, and T are all known. 
Please let me know what I should do. 

Thank you!
Virginia

**Comment by epnev** [comment]
Again, use debugging to see whether d1, d2 and T are defined inside the function

**Comment by vd2309** [comment]
Thanks! the reason was because the original code makes d1 and d2 empty, because options.d1 and options.d2 returns empty for both of the following commands
d1 = options.d1;
d2 = options.d2;
so i just commented these out and set d1=249; and d2=279; which are the correct numbers for our data 

Thank you! Your program is really amazing.  
Virginia

**Comment by epnev** [comment]
Glad it's resolved. In general you should pass the dimensions into the options structure since a lot of functions use them.
