### ISSUE TITLE
extracting spike rate from traces 

### ISSUE THREAD

**Issue by vd2309** [epnev/ca_source_extraction#29]
Hi!
I assume that the C_df output is the DF/F trace for each cell but I'm not sure how to extract the deconvolved spike rate from the data. The dataset contains about 300-400 neurons imagined with a 1photon microscope.

Is the S output the spike rate? If so how do the units for that output match up with spiking?

Thank you!

**Comment by epnev** [comment]
Hi @vd2309 
S is the neural spiking activity and it is proportional to the spike rates but with an unknown proportionality constant which is also different for each component. To get spikes you can either threshold S yourself, or you can use the slower 'MCMC' method for deconvolution by using options.deconv_method = 'MCMC'. Alternatively, if you know what effect a spike has in DF/F units you can use this to estimate your spike rates. 

Please don't create issues for questions that do not have to do with bugs or other issues with the software. Use the chat room https://gitter.im/epnev/ca_source_extraction instead.
