### ISSUE TITLE
bug in run_CNMF_patches

### ISSUE THREAD

**Issue by dpacheco0921** [epnev/ca_source_extraction#40]
P.psdx is already reshaped to either 2D or 3D, so from line 200 to 204 I think it should be like this:

if length(sizY) == 3
    X = P.psdx(:,:,1:min(size(P.psdx,3),500));
else
    X = P.psdx(:,:,:,1:min(size(P.psdx,4),500));
end

**Comment by epnev** [comment]
you're right, thanks!
