### ISSUE TITLE
bug in memmap_file

### ISSUE THREAD

**Issue by Enakcihc** [epnev/ca_source_extraction#53]
`memmap_file `uses the function `tiff_reader` with 3 arguments (filename, startingframe, num2read) and gives an error. Changing both instances (lines 33 & 60) of `tiff_reader `to `bigread2 `solved the issue.

**Comment by epnev** [comment]
Thanks again! Bear in mind bigread2 assumes that all entries all are non-negative and if your data has negative entries it will not work very well. You can also use the ```read_file``` that also reads are formats.
