### ISSUE TITLE
"N-dimensional indexing allowed for full matrices only."

### ISSUE THREAD

**Issue by m0userat25** [epnev/ca_source_extraction#54]
ran perfectly smoothly on mac os x yesterday on matlab 2016b
today when i downloaded from github the updated code and tried running on matlab 2016b pc, got following errors:
N-dimensional indexing allowed for full matrices only.

Error in classify_comp_corr (line 89)
    a_temp = a_temp(min(rows):max(rows),min(cols):max(cols),min(plns):max(plns));

Error in classify_components (line 36)
[rval_space,rval_time,ind_space,ind_time] = classify_comp_corr(Y,A,C,b,f,options);

Error in demo_script (line 64)
[ROIvars.rval_space,ROIvars.rval_time,ROIvars.max_pr,ROIvars.sizeA,keep] = classify_components(Y,A,C,b,f,YrA,options);

**Comment by epnev** [comment]
@m0userat25 
I introduce a bug in the function ```classify_comp_corr``` during some commits yesterday. This is now fixed. This is the only function that I changed, in case you don't want to re-download all the code.

**Comment by m0userat25** [comment]
thanks so much for the fix. it works now. sorry about my late response.
