### ISSUE TITLE
demo_3d.m throws error at update_spatial_components

### ISSUE THREAD

**Issue by aandreev0** [epnev/ca_source_extraction#55]
When running demo_3D.m I get error:

```
found 200 out of 200 neurons..
Refining initial estimates with HALS...Starting parallel pool (parpool) using the 'local' profile ... connected to 12 workers.
  done 

ans =

    0.2812    0.9953

Error using update_spatial_components (line 79)
When using options.spatial_method = regularized pass [A,b] as an
input and not just A

Error in demo_3D (line 61)
[A,b,Cin] = update_spatial_components(Yr,Cin,fin,Ain,P,options);
``` 

MATLAB R2015b, Win7

**Comment by epnev** [comment]
Thanks @aandreev0  
When you call the function ```update_spatial_components``` you need to replace input argument Ain with [Ain,bin]. This is now fixed in the demo_3D script

**Comment by aandreev0** [comment]
thanks for fixing. As I familiarize myself with codebase maybe will be able to contribute not just file bugs

**Comment by epnev** [comment]
you're welcome, and feel free to ask more questions and/or contribute!
