### ISSUE TITLE
Finding relevant coordinates from Coor variable for each file

### ISSUE THREAD

**Issue by HagaiHargil** [epnev/ca_source_extraction#60]
The `Coor` variable is generated by `plot_contours` in `run_pipeline.m`. For analysis and display purposes when running `run_pipeline` over more than one file, I'd like to take the coordinates only relevant for each specific file. Currently, probably due to my poor understanding of the code, I can't figure out how to filter the relevant coordinates of the current stack being analyzed.

Thanks!

**Comment by epnev** [comment]
In ```run_pipeline``` the assumption is that the set of components is common for all files that you analyze, although in certain files some of the components will be inactive. The ```Coor``` variable has the contour plots coordinates of all these components. If you want to select a subset of these coordinates, e.g., the first 5, you can simply use ```Coor(1:5)```. Does this answer your question, or do I misunderstand something?

**Comment by HagaiHargil** [comment]
Thanks for clarifying this bit. I wasn't aware that the FOV between all files has to be the same.
