### ISSUE TITLE
Implementation for neurofinder/spikefinder challenges

### ISSUE THREAD

**Issue by alexklibisz** [epnev/ca_source_extraction#64]
Have there been any submissions using this library for the neurofinder (http://neurofinder.codeneuro.org/) or spikefinder (http://spikefinder.codeneuro.org/) datasets?

**Comment by epnev** [comment]
@alexklibisz No; we did a submission to neurofinder with a much older version of the python code (https://github.com/simonsfoundation/caiman) about a year ago. Might repeat at some point.

**Comment by muschellij2** [comment]
Is http://spikefinder.codeneuro.org/ still there?
