### ISSUE TITLE
Error in register_ROI.m

### ISSUE THREAD

**Issue by masa6161** [epnev/ca_source_extraction#67]
Hello @epnev

I executed register_ROI.m with reference to a wiki for aligning ROIs of two different sessions, 
but I got an error at line 66.
`shifts_components = sparse(diag(1./sum(A2)))*A2'*shifts_fov;`

Apparently the mismatch of dimension numbers seems to be a problem.
Is this issue depended by a bug or a wrong usage?
I use image stacks which have 512x512 resolution and 78 and 69 of the spatial 
components were estimated by your algorithm.

If you have some idea or correction to this issue, I'm glad to be mentioned it.

**Comment by epnev** [comment]
@masa6161 Can you copy the exact error? I have a suspicion that it may be due to the way the variable shifts_fov is contructed. I changed that recently in the NoRMCorre package.

**Comment by masa6161** [comment]
@epnev  Thank you for quick reply.

I show exact messages below. 
> error using * Inner matrix dimensions must agree.
> error: register_ROIs (line 67)
>     shifts_components = sparse(diag(1./sum(A2)))*A2'*shifts_fov;

**Comment by epnev** [comment]
@masa6161  Thanks. This is weird, because the function seems to be working fine for me. What are the dimensions of the ```shifts_fov``` variable?

**Comment by masa6161** [comment]
@epnev First dimension is half of the elements that the first dimension of spatial component (in this case, 512x512/2) and second one is two.

**Comment by epnev** [comment]
@masa6161 That should be causing the problem. shifts_fov should be of size 512x512 (262144) in its first dimension. The sizes of the various variables should be as:

size(A1): [262144, 78]
size(A2): [262144, 69]
size(template1): [512,512]
size(template2): [512,512]
options_mc should be an options struct generated while running the motion correction algorithm.

If that's the case, then it's unclear what causes the problem. If you send me the inputs to the register_ROIs function I can take a quick look.

**Comment by masa6161** [comment]
@epnev Sizes of all inputs were identical shown as your mention. I seem that `shift_fov` are generated by reshaping a matrix (d1 x d2, 512 x 512) to a two-dimension matrix (row is two) using `shifts_fov = reshape(imresize(global_shift.shifts,[options.d1,options.d2]),[],2);`. So the generated matrix's first dimension might be 512x512/2, right?

Perhaps because my usage or inputs may be wrong, I'm glad to check the inputs I used.
https://www.dropbox.com/s/0vw086nl98fa5s3/data.mat?dl=0

**Comment by epnev** [comment]
@masa6161 Thanks. It seems that you don't have the latest version of the [NoRMCorre](https://github.com/simonsfoundation/NoRMCorre) package. With that the function ran without problems here. If you try it out you can manually set ```options_mc.shifts_method = 'fft'``` before running the ```register_ROIs``` function because there is an additional entry in the ```options_mc``` variable (or you can simply regenerate the variable). Let me know if that works. 

PS: The 2 in the second dimension of ```shifts_fov``` corresponds to the x and y directions

**Comment by masa6161** [comment]
@epnev Aha! It correctly works now. A cause was the old version of the NoRMCorre as you pointed out. I'm sorry for making elementary mistakes. 
I appreciate your great and kind supports!

**Comment by epnev** [comment]
@masa6161 You didn't make any mistake at all. It's my fault for not checking that function after updating normcorre. Thanks for pointing it out and I'm glad this is resolved now.
