### ISSUE TITLE
Error in demoscript

### ISSUE THREAD

**Issue by jk1224** [epnev/ca_source_extraction#9]
Hello,

I am having an issue with your demo script. First, in the utilities folder the graph_conn_comp_mex was .cpp and not .m, so I had to change this in order for the function to be recognized by matlab. If I left it as .cpp, matlab gave me an error saying the function "graph_con_comp_mex" was undefined. Now that I have changed this to graph_con_comp_mex.m, matlab recognizes the function but I am getting the following error:

Error: File: graph_conn_comp_mex.m Line: 1 Column: 1
The input character is not valid in MATLAB statements or expressions.

Error in graph_connected_comp (line 26)
[l c] = graph_conn_comp_mex(sA);

Error in merge_components (line 45)
[l,c] = graph_connected_comp(sparse(FF3+FF3'));     % extract connected components

Error in Sources2D/merge (line 65)
            [obj.A, obj.C, nr, merged_ROIs, obj.P, obj.S] = merge_components(...

Error in demo_script_class (line 61)
[K_m, merged_ROIs] = merge(obj, Yr);

Could you please explain?

Thank you

**Comment by epnev** [comment]
Hi,

graph_conn_comp.cpp is a C++ file that needs to be compiled and then called from graph_connected_comp.m I have included compiled version for 64bit windows/mac/linux machines

Try re-downloading the code and run it without changing the file extension and if this doesn't run try compiling the function yourself using the mex command.

Hope that helps!

**Comment by jk1224** [comment]
Thank you for the fast reply. So I should use the mex function in matlab to compile the .cpp file, then have the graph_connected_comp function utilize this instead of the .cpp? I'll give it a try, thanks!

**Comment by jk1224** [comment]
Thank you for the compiled files. I know that I need to use the mexw64 version, but it still doesn't seem to be working. It seems there is an issue with adding it to dependent libraries?

**Comment by epnev** [comment]
Have you tried compiling the file yourself? What sort of computing environment do you use?

**Comment by jk1224** [comment]
I have tried compiling the file myself and I have tried getting matlab to utilize the .mexw64 file. Unfortunately the code runs until the graph_connected_comp function and then repeatedly gives me the error that graph_conn_comp is not found or defined. Essentially I think the problem is that I have not correctly gotten matlab to recognize which file to use. I'm using a windows 8 computer, 64-bit.

**Comment by NTCColumbia** [comment]
Hi there! 

Do you have "graph_conn_comp.m" file? Inside this file, it will call graph_conn_comp_mex.mexw64. So the issue would be it cannot find "graph_conn_comp_mex.mexw64". If so, please type in "mex graph_conn_comp_mex.cpp" in the command window, and try it again. If something still goes wrong, could you copy the error message over?
